### ISSUE TITLE
Publish Date Incorrect on Articles

### ISSUE THREAD

**Issue by WHiT3R4bBiT** [ahgl/ahgl-site#127]
The two most recent articles show creation and publish dates of Dec 3 and Dec 23, but the homepage shows and sorts the dates as Nov 2 and Nov 1 respectively.

http://afterhoursgaming.tv/#/

**Comment by WHiT3R4bBiT** [comment]
This has now gotten worse - the newest article actually reads UNDEFINED 1, 2015 on our homepage http://afterhoursgaming.tv/#/, making the bug more visible.

**Comment by Dimitri-Gnidash** [comment]
@WHiT3R4bBiT I or @tumanyanani will look into this ASAP.
