### ISSUE TITLE
Weird formatting on match pages

### ISSUE THREAD

**Issue by WHiT3R4bBiT** [ahgl/ahgl-site#88]
For example:

http://vk812.gondor.co/starcraft-2-season-2/matches/185/

Currently looks like: https://www.dropbox.com/s/osuac6w752tzjeb/Screen%20Shot%202014-09-23%20at%2011.15.20%20AM.png?dl=0

Should look like (only header needs fixed, ignore the other graphics for now): https://www.dropbox.com/s/s7rsl445hfvvx58/AHGL5-mockup%5Bmatches%5DR2.jpg?dl=0

Using Header: https://www.dropbox.com/s/wjy8qoogdubu18w/section_header_centered.svg?dl=0
or: https://www.dropbox.com/s/7jt41npdiyt3pwj/section_header_centered.ai?dl=0

**Comment by noahm** [comment]
See pull request #133
